version: '3'

services:
    nginx:
        image: nginx:mainline-alpine
        volumes:
            # TODO: build the nginx configuration into the image
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
            - ./nginx/include:/etc/nginx/include:ro
            - ./html:/var/www/html:ro
            - ./log/nginx:/var/log/nginx
            - ./letsencrypt:/etc/letsencrypt:ro
        ports:
            - "443:443"
        restart: unless-stopped
    nginx-edge:
        image: nginx:mainline-alpine
        volumes:
            - ./html-edge:/var/www/html:ro
            - ./nginx-edge/nginx-edge.conf:/etc/nginx/nginx.conf:ro
            - ./log/nginx-edge:/var/log/nginx
        ports:
            - "80:80"
        restart: unless-stopped
    kolorskemo-client-staging:
        image: kolorskemo-client:staging
        volumes:
            - ./html/staging.kolorskemo.com:/app/client/build-out
    kolorskemo-server-staging:
        image: kolorskemo-server:staging
    kolorskemo-client-production:
        image: kolorskemo-client:production-latest
        volumes:
            - ./html/kolorskemo.com:/app/client/build-out
    kolorskemo-server-production:
        image: kolorskemo-server:production-latest
