version: '3'

services:
    nginx:
        #image: nginx:mainline-alpine
        build: https://github.com/alfa-bravo/kolorskemo-vue-setup.git
        volumes:
            # TODO: build the nginx configuration into the image
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
            - ./nginx/include:/etc/nginx/include:ro
            - ./html:/var/www/html
            - ./log/nginx:/var/log/nginx
            - ./letsencrypt:/etc/letsencrypt:ro
        ports:
            - "443:443"
        restart: unless-stopped
    nginx-edge:
        image: nginx:mainline-alpine
        volumes:
            - ./html-edge:/var/www/html:ro
            - ./nginx-edge/nginx-edge.conf:/etc/nginx/nginx.conf:ro
            - ./log/nginx-edge:/var/log/nginx
        ports:
            - "80:80"
        restart: unless-stopped